### ISSUE TITLE
Visitor can view items

### ISSUE THREAD

**Issue by bfpepper** [bfpepper/little-shop-1608#1]
Background: I have several items and each of them has a title, description, price, and image
As a visitor
When I visit "/items"
I can see all existing items

**Comment by bfpepper** [comment]
Background: I have several items and each of them has a title, description, price, and image
     As a visitor
     When I visit "/items"
     I can see all existing items

**Comment by rtravitz** [comment]
Need model test for trip method "to_param"

**Comment by bfpepper** [comment]
I got you bo!
