### ISSUE TITLE
Admin edits an item

### ISSUE THREAD

**Issue by bfpepper** [bfpepper/little-shop-1608#100]
Background: an existing item
     As an admin
     When I visit "admin/items"
     And I click "Edit"
     Then my current path should be "/admin/items/:ITEM_ID/edit"
     And I should be able to update title, description, image, and status

**Comment by antciccone** [comment]
@rtravitz  admin_can_edit_a_trip_spec looks like u test that u can update the title, price and status but not the image. not sure if that matters. if not we can mark this as completed.
