### ISSUE TITLE
Removing an item from my cart

### ISSUE THREAD

**Issue by bfpepper** [bfpepper/little-shop-1608#24]
Background: My cart has an item in it
     As a visitor
     When I visit "/cart"
     And I click link "Remove"
     Then my current page should be "/cart"
     And I should see a message styled in green
     And the message should say "Successfully removed SOME_ITEM from your cart."
     And the title "SOME_ITEM" should be a link to that item in case the user wants to add it back
     And I should not see the item listed in cart

**Comment by rtravitz** [comment]
Need message styled in green: "Successfully removed "some_item" from your cart." The words "some_item" must link back to the item in question in case the user wants to add it again. Update test to reflect that this message with link appears.

**Comment by bfpepper** [comment]
Got it
