### ISSUE TITLE
Adjusting the quantity of an item in the cart

### ISSUE THREAD

**Issue by bfpepper** [bfpepper/little-shop-1608#25]
Background: My cart has an item in it
     As a visitor
     When I visit "/cart"
     Then I should see my item with a quantity of 1
     And when I increase the quantity
     Then my current page should be '/cart'
     And that item's quantity should reflect the increase
     And the subtotal for that item should increase
     And the total for the cart should match that increase
     And when I decrease the quantity
     Then my current page should be '/cart'
     And that item's quantity should reflect the decrease
     And the subtotal for that item should decrease
     And the total for the cart should match that decrease

**Comment by rtravitz** [comment]
On the feature test for this functionality, we need to add an assertion that the subtotal for an item should change and the total should change.

The feature test in question is located at:
spec/features/carts/visitor_updates_the_quantity_of_an_item_in_their_cart_spec.rb

**Comment by antciccone** [comment]
cool ill grab this one

**Comment by rtravitz** [comment]
Card 4 needs to be done before this one can be tested properly

**Comment by antciccone** [comment]
-pretty sure this is the card with the JS that we can't test.
