### ISSUE TITLE
Authenticated User

### ISSUE THREAD

**Issue by bfpepper** [bfpepper/little-shop-1608#26]
As a visitor
   When I visit "/"
   Then I should see a link for "Login"
   And when I click "Login"
   And I should be on the "/login" page
   I should see a place to insert my credentials to login
   And I should see a link to "Create Account"

As a visitor 
   When I visit "/login
   And when I click link "Create Account"
   And I fill in my desired credentials
   And I submit my information
   Then my current page should be "/dashboard"
   And I should see a message in the navbar that says "Logged in as SOME_USER"
   And I should see my profile information
   And I should not see a link for "Login"
   And I should see a link for "Logout"

**Comment by rtravitz** [comment]
Flash message needs to say "Logged in as SOME_USER" after account creation. Currently it says "You have successfully created an account."

**Comment by bfpepper** [comment]
I'll take it. Should be done in a few.

**Comment by rtravitz** [comment]
change flash message to Logged in as Some User instead of the current message
