### ISSUE TITLE
Checking out

### ISSUE THREAD

**Issue by bfpepper** [bfpepper/little-shop-1608#59]
Background: An existing user and a cart with items
     As a visitor
     When I add items to my cart
     And I visit "/cart"
     And I click "Login or Register to Checkout"
     Then I should be required to login
     When I am logged in
     And I visit my cart
     And when I click "Checkout"
     Then the order should be placed
     And my current page should be "/orders"
     And I should see a message "Order was successfully placed"
     And I should see the order I just placed in a table

**Comment by rtravitz** [comment]
Change "Thank you for your order!" flash message to "Order was successfully placed"

Should we place the orders in a table as it recommends?

We have an extra page where they review their order confirmation. Do we care?
