### ISSUE TITLE
Authenticated users security

### ISSUE THREAD

**Issue by bfpepper** [bfpepper/little-shop-1608#60]
Background: An authenticated user 
     As an Authenticated User
     I cannot view another user's private data (current or past orders, etc)
     I cannot view the administrator screens or use admin functionality
     I cannot make myself an admin

**Comment by rtravitz** [comment]
Orders for another user can currently be viewed by going to /orders/:id. We need to lock this down. (This note also appears on card #29 Viewing a Past Order, so check to make sure it hasn't been done yet before taking on this card!)

**Comment by bfpepper** [comment]
I'll handle

**Comment by rtravitz** [comment]
I have this one

**Comment by rtravitz** [comment]
I'll take this one instead!
