### ISSUE TITLE
Admin User Dashboard

### ISSUE THREAD

**Issue by bfpepper** [bfpepper/little-shop-1608#62]
As an Admin
     When I visit "/admin/dashboard"
     I will see a heading on the page that says "Admin Dashboard"
     As a registered user
     When I visit "/admin/dashboard"
     I get a 404
     As an unregistered user
     When I visit "/admin/dashboard"
     I get a 404

**Comment by bfpepper** [comment]
We need to ensure that ANY 404 page does not have the application/layout template in there. Its an easy fix.

**Comment by rtravitz** [comment]
Is this one fixed already? @bfpepper @JStans12

**Comment by bfpepper** [comment]
Ya we're good.
